name: "Build Ghostty"

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  debian:
    name: "Build Ghostty for Debian Sid (Unstable)"
    runs-on: ubuntu-24.04
    permissions: write-all
    # Refer : https://stackoverflow.com/questions/64033686/how-can-i-use-private-docker-image-in-github-actions
    container: ghcr.io/vanilla-os/desktop:main
    
    steps:
      - name: "Checkout latest codebase"
        uses: actions/checkout@v3

      # Refer : https://ghostty.org/docs/install/build
      - name: "Install Depenencies"
        run: |
          apt-get update
          apt-get install -y build-essential git libgtk-4-dev libadwaita-1-dev

      # Refer : https://github.com/marketplace/actions/setup-zig-compiler
      - name: "Setup Zig"
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: "Clone Ghostty repo"
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'v1.0.1'
          owner: 'ghostty-org'
          repository: 'ghostty'

      - name: "Build Ghostty binary"
        run: cd ghostty && zig build -Doptimize=ReleaseFast && mv zig-out ghostty && tar -jcf ghostty-debian-sid-amd64.tar.bz2 ghostty

      - name: "List files"
        run: ls -liFh

      - name: "Create a release"
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.run.id }}
          tag_name: ${{ github.ref_name }}
          files: ghostty/ghostty-debian-sid-amd64.tar.bz2
